name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.24.1
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        run: GOOS=linux GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./... 

  deploy:
    name: Push Docker image to Docker hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: setup Docker buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to Docker hub
          uses: docker/login-action@v3
          with: 
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5.7.0
          with: 
            images: artwovk/hello-golang

        - name: Build and push Docker Image
          uses: docker/build-push-action@v6.15.0
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
